name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Compile all Java files in AbstractFactory.java/src
      run: |
        find "$GITHUB_WORKSPACE/Creational Design Patterns/Abstract Factory/AbstractFactory.java/src" -name "*.java" > files.txt
        while IFS= read -r file
        do
          javac -d bin "$file"
        done < files.txt
